#!/usr/bin/env python3
"""Validate and atomically install the calibration schema-v2 wrapper."""

import argparse
import hashlib
import json
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
PINNED_WRAPPER_SHA256 = (
    "54f99b5945bc860148001ee00dfed5b6af3b8528f5bfd38dea7f1431d3f2ae0a"
)
PINNED_LEGACY_SHA256 = (
    "8f54b7c23afe8fb1b0ecb5dca125318636d65c3ae0c78af005408d98accc42e3"
)
PINNED_PARAMS_SHA256 = (
    "b9654eb0659ca0f2481b89cd674001bd3748288d6dec58c13a107739cefc561d"
)
OPENFHE_VERSION = "1.5.0"
ROW_RE = re.compile(
    r'^\s*\{\{"(?:primary40|sensitivity64|feasibility128)", '
    r'Circuit::(?:OneHot|Sqrt), "[^"]+", '
    r'SecurityLevel::STD(?:128|192), [^{}]+'
    r'"[0-9a-f]{64}", "1\.5\.0"\}, [^{}]+\},$'
)
LOGICAL_KEY_RE = re.compile(
    r'^\s*\{\{"(?P<profile>primary40|sensitivity64|feasibility128)", '
    r'Circuit::(?P<circuit>OneHot|Sqrt), "(?P<shape>[^"]+)", '
    r'SecurityLevel::(?P<security>STD128|STD192), '
    r'(?P<requested>[0-9]+), (?P<depth>[0-9]+), '
    r'"(?P<consumer>[0-9a-f]{64})", '
    r'"(?P<openfhe>[^"]+)"\},'
)


def sha256_file(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def regular_file(path, label):
    try:
        info = path.lstat()
    except FileNotFoundError as error:
        raise ValueError(f"{label} is missing") from error
    if (
        not stat.S_ISREG(info.st_mode)
        or path.is_symlink()
        or info.st_nlink != 1
    ):
        raise ValueError(f"{label} must be a regular non-symlink file")


def validate_wrapper(path):
    regular_file(path, "staged wrapper")
    if sha256_file(path) != PINNED_WRAPPER_SHA256:
        raise ValueError("pinned wrapper hash mismatch")


def validate_legacy(path):
    regular_file(path, "legacy rows")
    if sha256_file(path) != PINNED_LEGACY_SHA256:
        raise ValueError("pinned legacy hash mismatch")
    rows = [
        line for line in path.read_text().splitlines()
        if line.lstrip().startswith("{Circuit::")
    ]
    if len(rows) != 303:
        raise ValueError("legacy row count mismatch")
    for row in rows:
        if "SecurityLevel::TOY" in row:
            continue
        if (
            "Circuit::Threshold" not in row
            or "SecurityLevel::STD" not in row
        ):
            raise ValueError("legacy contains an STD pre-threshold row")


def validate_expanded(path):
    regular_file(path, "pre-threshold rows")
    text = path.read_text()
    lines = text.splitlines()
    if (
        len(lines) < 34
        or lines[0]
        != "// Generated by scripts/make_calibration_table.py; do not edit."
        or re.fullmatch(
            r"// finalized manifest sha256: [0-9a-f]{64}", lines[1])
        is None
    ):
        raise ValueError("expanded fragment role lacks manifest binding")
    if "Circuit::Threshold" in text or "SecurityLevel::TOY" in text:
        raise ValueError("expanded fragment role contains legacy row")
    candidate_lines = lines[2:]
    if not 32 <= len(candidate_lines) <= 68:
        raise ValueError("expanded fragment role row count is invalid")
    if len(candidate_lines) != len(set(candidate_lines)):
        raise ValueError("expanded fragment contains duplicate rows")
    logical_keys = set()
    for line in candidate_lines:
        if ROW_RE.fullmatch(line) is None:
            if (
                line.lstrip().startswith("{{")
                and OPENFHE_VERSION not in line
            ):
                raise ValueError("expanded fragment OpenFHE version mismatch")
            raise ValueError("expanded fragment role/schema mismatch")
        if line.count(f'"{OPENFHE_VERSION}"') != 1:
            raise ValueError("expanded fragment OpenFHE version mismatch")
        match = LOGICAL_KEY_RE.match(line)
        if match is None:
            raise ValueError("expanded fragment logical key parse mismatch")
        logical_key = (
            match["profile"],
            {"OneHot": "onehot", "Sqrt": "sqrt"}[match["circuit"]],
            match["shape"],
            match["security"],
            int(match["requested"]),
            int(match["depth"]),
            match["consumer"],
            match["openfhe"],
        )
        if logical_key in logical_keys:
            raise ValueError("expanded fragment contains duplicate logical key")
        logical_keys.add(logical_key)
    matrix = json.loads((REPO / "scripts" / "noise_profiles.json").read_text())
    canonical = {
        (
            partition["profile_id"],
            partition["circuit"],
            partition["shape_id"],
            partition["security"],
            partition["requested_ring_dim"],
            partition["natural_depth"],
            partition["consumer_set_sha256"],
            partition["openfhe_version"],
        )
        for partition in matrix["partitions"]
    }
    if not logical_keys.issubset(canonical):
        raise ValueError("expanded fragment contains an extra logical key")
    missing = canonical - logical_keys
    if (
        len(missing) > 2
        or any(key[0] != "feasibility128" for key in missing)
    ):
        raise ValueError("expanded fragment is missing a required logical key")


def compile_and_run_probes(wrapper, legacy, expanded):
    if sha256_file(REPO / "src" / "util" / "params.cpp") != PINNED_PARAMS_SHA256:
        raise ValueError("frozen params.cpp compile transition mismatch")
    compiler_name = os.environ.get("CXX", "c++")
    compiler = shutil.which(compiler_name)
    if compiler is None:
        raise ValueError("compile failed: CXX is unavailable")
    sources = [
        REPO / "src" / "util" / "params.cpp",
        REPO / "src" / "util" / "params_calibration.cpp",
        REPO / "src" / "util" / "security_profile.cpp",
        REPO / "tests" / "fixtures" /
        "noise_calibration_cutover_probe.cpp",
    ]
    with tempfile.TemporaryDirectory(prefix="piccard-cutover-compile-") as tmp:
        stage = Path(tmp)
        (stage / "include" / "util").mkdir(parents=True)
        (stage / "scripts" / "templates").mkdir(parents=True)
        (stage / "tests" / "fixtures").mkdir(parents=True)
        staged_wrapper = (
            stage / "scripts" / "templates" /
            "noise_calibration_wrapper.inc"
        )
        staged_legacy = (
            stage / "include" / "util" /
            "noise_calibration_legacy_rows.inc"
        )
        staged_expanded = (
            stage / "tests" / "fixtures" /
            "noise_calibration_pre_threshold_rows.inc"
        )
        shutil.copyfile(wrapper, staged_wrapper)
        shutil.copyfile(legacy, staged_legacy)
        shutil.copyfile(expanded, staged_expanded)

        common = [
            compiler,
            "-std=c++17",
            "-O0",
            "-I" + str(REPO / "include"),
            "-I" + str(REPO),
            *(str(source) for source in sources),
        ]
        current = stage / "probe-current"
        current_compile = subprocess.run(
            [*common, "-o", str(current)],
            text=True,
            capture_output=True,
        )
        if current_compile.returncode != 0:
            raise ValueError(
                "current compile failed: " + current_compile.stderr.strip())
        current_run = subprocess.run(
            [str(current)], text=True, capture_output=True)
        if (
            current_run.returncode != 0
            or "current V2 table coverage inactive" not in current_run.stdout
        ):
            raise ValueError(
                "current probe regression: "
                + (current_run.stderr or current_run.stdout).strip())

        v2 = stage / "probe-v2"
        v2_compile = subprocess.run(
            [
                compiler,
                "-std=c++17",
                "-O0",
                "-I" + str(stage),
                "-I" + str(REPO / "include"),
                "-I" + str(REPO),
                "-DPICCARD_PRE_THRESHOLD_CALIBRATION_V2=1",
                "-DPICCARD_NOISE_CALIBRATION_FILE="
                f'"{staged_wrapper}"',
                "-DPICCARD_PRE_THRESHOLD_CALIBRATION_ROWS_FILE="
                f'"{staged_expanded}"',
                *(str(source) for source in sources),
                "-o", str(v2),
            ],
            text=True,
            capture_output=True,
        )
        if v2_compile.returncode != 0:
            raise ValueError(
                "V2 compile failed: " + v2_compile.stderr.strip())
        v2_run = subprocess.run([str(v2)], text=True, capture_output=True)
        if (
            v2_run.returncode != 0
            or re.fullmatch(
                r"V2 required=34 selected=(?:32|33|34) "
                r"infeasible=(?:2|1|0) missing=0\n",
                v2_run.stdout,
            ) is None
        ):
            raise ValueError(
                "V2 probe regression: "
                + (v2_run.stderr or v2_run.stdout).strip())


def fsync_directory(path):
    descriptor = os.open(path, os.O_RDONLY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def apply_cutover(wrapper, legacy, expanded, destination):
    if not destination.is_absolute():
        raise ValueError("--dest must be absolute")
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(
        "." + destination.name + ".piccard-cutover-v1.tmp")
    if temporary.exists() or temporary.is_symlink():
        raise ValueError("pre-existing cutover temp collision")
    validate_wrapper(wrapper)
    validate_legacy(legacy)
    validate_expanded(expanded)
    compile_and_run_probes(wrapper, legacy, expanded)

    descriptor = None
    owned = False
    try:
        descriptor = os.open(
            temporary,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL,
            0o644,
        )
        owned = True
        data = wrapper.read_bytes()
        offset = 0
        while offset < len(data):
            offset += os.write(descriptor, data[offset:])
        os.fsync(descriptor)
        os.close(descriptor)
        descriptor = None
        os.replace(temporary, destination)
        owned = False
        fsync_directory(destination.parent)
    finally:
        if descriptor is not None:
            os.close(descriptor)
        if owned:
            temporary.unlink(missing_ok=True)
    return hashlib.sha256(expanded.read_bytes()).hexdigest()


def parse_args(arguments):
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument("--staged-wrapper", required=True)
    parser.add_argument("--legacy-rows", required=True)
    parser.add_argument("--pre-threshold-rows", required=True)
    parser.add_argument("--dest", required=True)
    return parser.parse_args(arguments)


def main(arguments=None):
    args = parse_args(sys.argv[1:] if arguments is None else arguments)
    digest = apply_cutover(
        Path(args.staged_wrapper),
        Path(args.legacy_rows),
        Path(args.pre_threshold_rows),
        Path(args.dest),
    )
    print(f"pre-threshold fragment sha256: {digest}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError) as error:
        print(f"calibration cutover failed: {error}", file=sys.stderr)
        raise SystemExit(1)
